channels:
- conda-forge
dependencies:
- python=3.10.5
- pip<=24.0
- pip:
  - mlflow==2.11.3
  - cloudpickle==2.2.1
  - numpy==1.26.4
  - packaging==24.0
  - psutil==5.9.0
  - pyyaml==6.0
  - scikit-learn==1.1.1
  - scipy==1.12.0
name: mlflow-env
